### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by b4go3s** [YapengTian/ICIP2016#1]
can you share training code

**Comment by YapengTian** [comment]
The repository has already contained the training code. Please look at the DemoSR.m.

**Comment by b4go3s** [comment]
dear

oke thanks

i try run DemoSR.m and working, but if i try run TestImageSR.m i've got error the last code

"Error using save"
cannot create 'score.mat' because 'Set5Result' does not exist.

i'm Phd student in BIT beijing institute of technology, i'm interest about your research maybe next time we can discuss.
this my email
bagus_hardian_syah@bit.edu.cn
bagoeshardiansyah@gmail.com (i'm always using this email)

**Comment by YapengTian** [comment]
Sure.

**Comment by dundee98** [comment]
> dear
> 
> oke thanks
> 
> i try run DemoSR.m and working, but if i try run TestImageSR.m i've got error the last code
> 
> "Error using save" cannot create 'score.mat' because 'Set5Result' does not exist.
> 
> i'm Phd student in BIT beijing institute of technology, i'm interest about your research maybe next time we can discuss. this my email [bagus_hardian_syah@bit.edu.cn](mailto:bagus_hardian_syah@bit.edu.cn) [bagoeshardiansyah@gmail.com](mailto:bagoeshardiansyah@gmail.com) (i'm always using this email)

hello
    you said you've run the demoSR.m successfully ,how long did you  cost?i try to run this code ,but failed ,could you pls share you code,thks a lot!!!
